# Cloud Build configuration for Moments Face Tagging Service
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/moments-face-tagging:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/moments-face-tagging:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'moments-face-tagging'
    - '--image'
    - 'gcr.io/$PROJECT_ID/moments-face-tagging:$COMMIT_SHA'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--memory'
    - '4Gi'
    - '--cpu'
    - '2'
    - '--timeout'
    - '900'
    - '--max-instances'
    - '10'
    - '--min-instances'
    - '0'
    - '--concurrency'
    - '80'
    - '--port'
    - '8080'
    - '--set-env-vars'
    - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID,ENVIRONMENT=production,USE_GPU=false,FACE_RECOGNITION_ENABLED=true,BACKGROUND_PROCESSING_ENABLED=true,PYTHONHASHSEED=0,MALLOC_TRIM_THRESHOLD_=131072'
    - '--cpu-boost'
    - '--startup-cpu-boost'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/moments-face-tagging:$COMMIT_SHA'

# Build options
options:
  machineType: 'E2_HIGHCPU_8'  # Use high-CPU machine for faster builds
  diskSizeGb: 100
  logging: CLOUD_LOGGING_ONLY

